local QuizData = {
	Circle = {
		{
			Question = 'What is 2 - 3?',
			Answers = {
				[-1] = true,
				[1] = false,
				[19] = false
			}
		},
		{
			Question = 'What is 7 x 8?',
			Answers = {
				[56] = true,
				[8] = false,
				[49] = false
			}
		},
		{
			Question = 'What is 9',
			Answers = {
				[19] = true,
				[9] = false,
				[10] = false
			}
		},
		{
			Question = 'What is 10 / 100?',
			Answers = {
				[0.1] = true,
				[10] = false,
				[100] = false
			}
		},
		{
			Question = 'What is 10 / 10?',
			Answers = {
				[1] = true,
				[10] = false,
				[0.1] = false
			}
		},
		{
			Question = 'What is π?',
			Answers = {
				[3.14159] = true,
				[3] = false,
				[134] = false
			}
		},
		{
			Question = 'Choose the correct option',
			Answers = {
				['Oreo'] = true,
				['What?'] = false,
				['Yes'] = false
			}
		}
	},
	Thavel = {
		{
			Question = 'What is Brazil\'s official language?',
			Answers = {
				['Portuguese'] = true,
				['Spanish'] = false,
				['French'] = false
			}
		},
		{
			Question = 'Which language has the most native speakers in the world?',
			Answers = {
				['Mandarin'] = true,
				['English'] = false,
				['Spanish'] = false
			}
		},
		{
			Question = 'What is Money called in Spanish?',
			Answers = {
				['Dinero'] = true,
				['Cash'] = false
			}
		},
		{
			Question = 'What is an example of a Metaphor?',
			Answers = {
				['This test was a piece of cake!'] = true,
				['This test is difficult!'] = false
			}
		}
	},
	Bloomie = {
		{
			Question = 'What is the powerhouse of a cell?',
			Answers = {
				['Mitochondria'] = true,
				['A cell'] = false,
				['Sunlight'] = false
			}
		},
		{
			Question = 'What is when a tadpole transforms into a frog?',
			Answers = {
				['Metamorphosis'] = true,
				['Transform'] = false,
				['Grow'] = false
			}
		},
		{
			Question = 'All living things are made up of cells',
			Answers = {
				['True'] = true,
				['False'] = false
			}
		},
		{
			Question = 'What is when a plant uses sunlight to grow?',
			Answers = {
				['Photosynthesis'] = true,
				['Metamorphosis'] = false,
				['Mitochondria'] = false
			}
		},
		{
			Question = 'What is the largest mammal on Earth?',
			Answers = {
				['Blue Whale'] = true,
				['Elephant'] = false,
				['Tiger'] = false
			}
		},
		{
			Question = 'Which isn\'t a characteristic of life?',
			Answers = {
				['Sentience'] = true,
				['Maintains homeostasis'] = false,
				['Responds to stimuli'] = false
			}
		},
		{
			Question = 'Which symbol represents silver?',
			Answers = {
				['Ag'] = true,
				['Au'] = false,
				['Sr'] = false
			}
		},
		{
			Question = 'At what temperature does water freeze',
			Answers = {
				['32'] = true,
				['0'] = false,
				['15'] = false
			}
		}
	},
	Emily = {
		{
			Question = 'Who was the 1st president of the United States?',
			Answers = {
				['George W'] = true,
				['James M'] = false,
				['Abraham L'] = false
			}
		},
		{
			Question = 'Which era marked a switch from agricultural practices to industrial practices?',
			Answers = {
				['Industrial Revolution'] = true,
				['Digital Revolution'] = false
			}
		},
		{
			Question = 'What ended in 1985?',
			Answers = {
				['oreo'] = true,
				['1984'] = false
			}
		},
		{
			Question = 'When was Hersheys founded?',
			Answers = {
				['1894'] = true,
				['1984'] = false,
				['1900'] = false
			}
		},
		{
			Question = 'When did World War 1 start?',
			Answers = {
				['1914'] = true,
				['1913'] = false,
				['1984'] = false
			}
		}
	},
	Sasha = {
		{
			Question = 'Which colors make up Orange?',
			Answers = {
				['Yellow & Red'] = true,
				['Red & Brown'] = false,
				['Brown & Yellow'] = false
			}
		},
		{
			Question = 'Which one of the following is a primary color?',
			Answers = {
				['Blue'] = true,
				['Green'] = false,
				['Purple'] = false
			}
		},
		{
			Question = 'What is the drawing technique that creates the illusion of depth on a flat surface?',
			Answers = {
				['Perspective'] = true,
				['Shading'] = false,
				['Stippling'] = false
			}
		},
		{
			Question = 'What is the complimentary color to Purple?',
			Answers = {
				['Yellow'] = true,
				['Green'] = false,
				['Blue'] = false
			}
		}
	},
	Demi = {
		{
			Question = 'Which of the following is not a note in the musical scale?',
			Answers = {
				['H'] = true,
				['G'] = false,
				['D'] = false,
				['B'] = false
			}
		},
		{
			Question = 'A Treble clef is used for illustrating notes that are:',
			Answers = {
				['Higher'] = true,
				['Lower'] = false
			}
		},
		{
			Question = 'A staff consists of how many horizontal lines?',
			Answers = {
				['Five'] = true,
				['Four'] = false,
				['Three'] = false
			}
		},
		{
			Question = 'How many notes are in the scale?',
			Answers = {
				['Eight'] = true,
				['Seven'] = false,
				['Six'] = false,
				['Nine'] = false
			}
		},
		{
			Question = 'Which of the following markings would affect the length of a note?',
			Answers = {
				['Dot'] = true,
				['Sharp'] = false,
				['Double-Sharp'] = false,
				['Flat'] = false
			}
		}
	}
}

return QuizData