return {
	{
		Name = 'Watch',
		DisplayName = 'Watch',
		Description = 'A digital wrist watch used to tell the time.',
		Icon = 18128061616,
		Price = 20,
		SellCut = 50,
		MaxLimit = 1
	}, {
		Name = 'HealPotion',
		DisplayName = 'Healing Potion',
		Description = 'Consume once to restore 40 hp. Great for recovery!',
		Icon = 17533420846,
		Price = 50,
		SellCut = 50,
		MaxLimit = 1
	}, {
		Name = 'OreoBar',
		DisplayName = 'Oreo Bar',
		Description = 'Miss Circle\'s favorite snack! Consume for a burst of energy!',
		Icon = 17533678060,
		Price = 50,
		SellCut = 50,
		MaxLimit = 1
	}, {
		Name = 'Floatie',
		DisplayName = 'Pool Floatie',
		Description = 'An inflatable pool floatie! \nUpon blocking with it, apply a heavy stun.',
		Icon = 18225659349,
		Price = 50,
		SellCut = 50,
		MaxLimit = 1
	}, {
		Name = 'Polaroid',
		DisplayName = 'Polaroid Camera',
		Description = 'Say cheese! Flash teachers with a bright light to temporarily stun them!',
		Icon = 17896895433,
		Price = 350,
		SellCut = 50,
		MaxLimit = 1
	}, {
		Name = 'Bat',
		DisplayName = 'Baseball Bat',
		Description = 'BONK! Strike a teacher with a blunt object! Perfect for self defense!',
		Icon = 17533414616,
		Price = 500,
		SellCut = 50,
		MaxLimit = 1
	}
}